#  UC4 - Estatística aplicada à Inteligência Artificial


## Aula 1 - Introdução à Estatística

---

###  Objetivo da aula
- Entender o que é estatística
- Entender o papel da estatística na IA
- Classificar tipos de dados

---
 **Mensagem importante:**
> IA não é só código. IA é entender dados.

# O que é Estatística?

Estatística é a área que trabalha com:

- Coleta de dados
- Organização de dados
- Análise de dados
- Tomada de decisão

---

## Exemplos

- Média de notas → aprovação
- Consumo → recomendação
- Padrões → detecção de fraude

O objetivo da estatística é transformar dados em informação para apoiar decisões.

---

## Dado x Informação

### Dado
É um valor bruto, sem contexto.

Exemplos:
- 25
- 3000
- "DF"

### Informação
É o dado interpretado com significado.

Exemplos:
- 25 anos de idade
- salário de 3000 reais
- mora em São Paulo

---

## População e Amostra

### População
É o conjunto total de elementos que queremos estudar.

Exemplo:
- todos os alunos de uma escola
- todos os clientes de uma empresa

---

### Amostra
É uma parte da população utilizada para análise. Um subconjunto da populacao

Exemplo:
- 30 alunos de uma turma
- 100 clientes selecionados

---

### Tipos de amostragem (o mais importante)
1. Amostragem aleatória simples
* Todos têm a mesma chance de ser escolhidos

Exemplo:

sortear nomes de uma lista

(É o método mais correto)

----
2. Amostragem por conveniência

(Escolhe quem está mais fácil)

Exemplo:

entrevistar só quem está na sala

Problema: pode gerar viés

3. Amostragem estratificada

(Divide a população em grupos e pega um pouco de cada)

Exemplo:

homens e mulheres
diferentes idades

(Muito usada em pesquisa)

-----
4. Amostragem sistemática

(Seleciona de forma regular)

Exemplo:

a cada 10 pessoas, escolhe 1

# Estatística na Inteligência Artificial

A IA depende da estatística para funcionar.

| Etapa | Uso da estatística |
|------|------------------|
| Coleta | Organização de dados |
| Treinamento | Cálculo de padrões |
| Avaliação | Medidas de erro |
| Decisão | Probabilidade |

---

Sem estatística, a IA não consegue aprender.

# Tipos de Dados

## Variável

Variável é qualquer característica que pode ser observada ou medida.

Exemplos:
- idade
- salário
- cidade
- nota

---



## Variáveis Qualitativas

- Não são numéricas (ou não fazem sentido calcular)
- Representam categorias

Ex:
- Nome
- Cor
- Cidade
- Estado civil

---

## Variáveis Quantitativas

- São numéricas
- Permitem cálculos

Ex:
- Idade
- Salário
- Altura
- Quantidade

## Variáveis Quantitativas (Subtipos)

###  Discretos
- Valores inteiros
- Contáveis

Ex:
- Número de filhos
- Número de compras

---

###  Contínuos
- Podem ter qualquer valor
- Incluem decimais

Ex:
- Altura
- Peso
- Temperatura

## Variáveis Qualitativas (Subtipos)

### Nominais
- Não possuem ordem
- - Ex: cor, cidade, gênero

### Ordinais
- Possuem ordem
- - Ex: escolaridade, satisfação, ranking

In [ ]:
import pandas as pd
dados = {
    "nome": ["Ana", "Bruno", "Carlos"],
    "idade": ["23","35","29"],
    "salario": ["2500.50", "3200", "4100.75"],
    "cidade": ["DF", "RJ", "SP"]
}

df = pd.DataFrame(dados)
df

     nome idade  salario cidade
0     Ana    23  2500.50     DF
1   Bruno    35     3200     RJ
2  Carlos    29  4100.75     SP

# Análise

Responda:

1. Qual coluna é qualitativa?
2. Qual coluna é quantitativa?
3. Qual coluna representa valores contínuos?

---

 Escreva suas respostas abaixo:

In [ ]:
# Resposta
print("1. nome && cidade")
print("2. idade && salario")
print("3. salario")

1. nome && cidade
2. idade && salario
3. salario

# Exercício 1

Classifique:

| Dado | Tipo |
|------|-----|
| Nome | qualitativa|
| Idade | quantitativa discreta |
| Salário | quantitativa continua |
| Cor favorita | qualitativa nominal |
| Número de filhos |qualitativa discreta |

# Exercício 2

Classifique como:

- Qualitativo
- Quantitativo discreto
- Quantitativo contínuo

| Dado | Tipo |
|------|-----|
| Altura | quantitativa continua|
| Número de alunos |quantitativa discreta |
| Temperatura | quantitativa continua |
| Salário | quantitativa continua|

In [ ]:
# Vamos criar outro dataset para prática
dados2 = {
    "produto": ["Arroz", "feijao", "Macarrao"],
    "preco": [16.00, 6.50, 5.50 ],
    "quantidade_venda": [10, 50, 30],
    "categoria": ["grao", "grao",  "massa"]
  }

pd2 = pd.DataFrame(dados2)
pd2

    produto  preco  quantidade_venda categoria
0     Arroz   16.0                10      grao
1    feijao    6.5                50      grao
2  Macarrao    5.5                30     massa

In [ ]:
pd2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   produto           3 non-null      object
 1   preco             3 non-null      float64
 2   quantidade_venda  3 non-null      int64
 3   categoria         3 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
pd2.describe()

           preco  quantidade_venda
count   3.000000               3.0
mean    9.333333              30.0
std     5.795113              20.0
min     5.500000              10.0
25%     6.000000              20.0
50%     6.500000              30.0
75%    11.250000              40.0
max    16.000000              50.0

#  Exercício 3

Classifique cada coluna do dataset acima:

- produto
- preco
- quantidade_vendida
- categoria

## Reforço

###Classifique os dados abaixo:

- CPF = qualitativa
- Temperatura = quantitativa continua
- Placa de carro = qualitativa
- Altura = quantitativa discreta
- Número de curtidas no Instagram = quantitativa discreta
- CEP = qualitativa
- Salário = quantitativa
- Tipo sanguíneo = qualitativa

### Se você fosse criar uma IA para recomendar filmes, quais dados você usaria?

### Explorando dados no Python

- ´df.info´ e ´df.describe()´

### Desafio final

In [ ]:
dados = {
    "idade": [18, 25, 40, 60],
    "compra": ["sim", "sim", "não", "não"]
}

Se chega uma pessoa com 30 anos, ela compraria?

“Com base em quê?”

“Achismo ou dados?”

“Nosso cérebro quer encontrar padrão rápido.
Mas a estatística exige evidência.”

“Com poucos dados, a IA também erra.”

Você pode falar:

“Se tivéssemos MUITOS dados, poderíamos modelar isso”

Exemplo:

regressão (idade vs compra)
probabilidade condicional

Aí você conecta com IA de verdade

#  Conclusão

Hoje você aprendeu:

- O que é estatística
- A importância dela na IA
- Tipos de dados
- Discreto vs contínuo

---

 Na próxima aula:
Vamos começar a analisar dados de verdade (média, moda, etc).

---

 Lembre-se:
> IA começa com entender dados.